# Generated by Django 3.0 on 2022-06-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220604_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasport',
            name='random_son',
            field=models.BigIntegerField(default=7482339),
        ),
    ]
