# Generated by Django 3.0 on 2022-06-04 16:52

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220604_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasport',
            name='ielts_sertifikat',
            field=models.ImageField(blank=True, help_text='Rasm maks. 5MB', null=True, upload_to='static/ielts/', validators=[myapp.models.validate_file], verbose_name='IELTS sertifikati'),
        ),
        migrations.AlterField(
            model_name='pasport',
            name='random_son',
            field=models.BigIntegerField(default=9553651),
        ),
    ]
